/*
 * board_init_ext.h
 *
 * Расширение инициализации платы — файл НЕ генерируется Config Tools.
 * Располагается в source/inverter/ и не затрагивается при регенерации board/.
 *
 * Использование в main():
 *   BOARD_HardwareInit();   // вместо BOARD_InitBootPeripherals()
 */

#ifndef BOARD_INIT_EXT_H_
#define BOARD_INIT_EXT_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Полная инициализация аппаратуры:
 *   1. CLOCK_EnableClock для DMA0/DMAMUX/FTM1/ADC0/PDB0
 *   2. BOARD_InitPeripherals() — generated by Config Tools
 *   3. FTM1 MOD коррекция (center-aligned 20 кГц → MOD=2999)
 *   4. TRGMUX: FTM1 InitTrigger → PDB0
 *   5. PDB0: moduloValue=750, IDLY=5, ADC pre-trigger delay=375
 *
 * Вызывать ПОСЛЕ BOARD_InitBootPins() и BOARD_InitBootClocks(),
 * ВМЕСТО BOARD_InitBootPeripherals().
 */
void BOARD_HardwareInit(void);

#ifdef __cplusplus
}
#endif

#endif /* BOARD_INIT_EXT_H_ */
