/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "stdlib.h"
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_ftm.h"
#include "fsl_adc12.h"
#include "fsl_pdb.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA_DMAMUX_BASEADDR DMAMUX
/* DMA interrupt vector ID (number). */
#define DMA_DMA_INT_ERROR_IRQN DMA_Error_IRQn
/* DMA interrupt handler identifier. */
#define DMA_DMA_INT_ERROR_IRQHANDLER DMA_Error_IRQHandler

  /* Channel CH0 definitions */
/* DMA eDMA source request. */
#define DMA_CH0_DMA_REQUEST kDmaRequestMux0PDB0
/* Selected eDMA channel number. */
#define DMA_CH0_DMA_CHANNEL 0
/* TCD pool size */
#define DMA_CH0_TCD_SIZE 2
/* DMA interrupt vector ID (number). */
#define DMA_DMA_CH_INT_DONE_0_IRQN DMA0_IRQn
/* DMA interrupt vector priority. */
#define DMA_DMA_CH_INT_DONE_0_IRQ_PRIORITY 0
/* DMA channel interrupt request. */
#define DMA_CH0_IRQ_REQUEST kEDMA_ErrorInterruptEnable
/* Definition of peripheral ID */
#define FTM1_PERIPHERAL FTM1
/* Definition of the clock source frequency */
#define FTM1_CLOCK_SOURCE 120000000UL
/* Definition of the clock source frequency */
#define FTM1_TIMER_MODULO_VALUE 5999
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* ADC0 interrupt vector ID (number). */
#define ADC0_IRQN ADC0_IRQn
/* ADC0 interrupt handler identifier. */
#define ADC0_IRQHANDLER ADC0_IRQHandler
/* BOARD_InitPeripherals defines for PDB0 */
/* Definition of peripheral ID */
#define PDB0_PERIPHERAL PDB0
/* Number of the CMP widow sample pulse out configuration */
#define PDB0_DAC_TRIGGERS_COUNT 0
/* Number of the CMP widow sample pulse out configuration */
#define PDB0_CMP_PULSE_OUT_COUNT 0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA_config;
extern edma_handle_t DMA_CH0_Handle;
/* Transactional transfer configuration */
extern edma_transfer_config_t DMA_CH0_TRANSFER0_config;
/* Transactional transfer configuration */
extern edma_transfer_config_t DMA_CH0_TRANSFER1_config;
extern const ftm_config_t FTM1_config;
extern const adc12_config_t ADC0_config;
extern adc12_channel_config_t ADC0_channelsConfig[1];
extern const adc12_hardware_average_mode_t ADC0_hardwareAverageConfig;
extern const pdb_config_t PDB0_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* eDMA callback function for the 0 channel.*/
extern void DMA_callback(edma_handle_t*, void*, bool, uint32_t);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
