/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MKE18F512xxx16
package_id: MKE18F512VLH16
mcu_data: ksdk2_0
processor_version: 13.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 8fa5bfb5-9694-430d-b49e-a5373e09420b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/* DMA (eDMA0 / DMAMUX) инициализируется в board_init_ext.c :: prv_DMA_Init()
 * DMA instance в .mex отключён (enabled=false) во избежание регенерации
 * кода с malloc/PrepareTransfer/SubmitTransfer из Config Tools. */

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * FTM1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FTM1'
- type: 'ftm'
- mode: 'EdgeAligned'
- custom_name_enabled: 'false'
- type_id: 'ftm_cf73470dab578a761c1bb272554a7d11'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FTM1'
- config_sets:
  - ftm_main_config:
    - ftm_config:
      - clockSource: 'kFTM_FixedClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - timerPrescaler: '1'
      - timerOutputFrequency: '20 kHz'
      - systemClockSource: 'BusInterfaceClock'
      - systemClockSourceFreq: 'ClocksTool_DefaultInit'
      - faultMode: 'kFTM_Fault_Disable'
      - inputFilterPeriod: '1'
      - faultInputs:
        - 0:
          - enableFaultInput: 'false'
          - faultLevelVal: 'low'
          - useFaultFilter: 'false'
        - 1:
          - enableFaultInput: 'false'
          - faultLevelVal: 'low'
          - useFaultFilter: 'false'
        - 2:
          - enableFaultInput: 'false'
          - faultLevelVal: 'low'
          - useFaultFilter: 'false'
        - 3:
          - enableFaultInput: 'false'
          - faultLevelVal: 'low'
          - useFaultFilter: 'false'
      - deadTimePrescale: 'kFTM_Deadtime_Prescale_1'
      - deadTimePeriod: '12'
      - pwmSyncMode: 'kFTM_SoftwareTrigger'
      - reloadPoints: ''
      - extTriggers: 'kFTM_InitTrigger'
      - chnlInitState: ''
      - chnlPolarity: ''
      - bdmMode: 'kFTM_BdmMode_0'
      - useGlobalTimeBase: 'false'
    - timer_interrupts: ''
    - enable_irq: 'false'
    - ftm_interrupt:
      - IRQn: 'FTM1_IRQn'
      - enable_interrrupt: 'disabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'false'
  - ftm_edge_aligned_mode:
    - ftm_edge_aligned_channels_config:
      - 0:
        - channelId: ''
        - edge_aligned_mode: 'kFTM_CombinedPwm'
        - combined_pwm:
          - chnlNumber: 'kFTM_Chnl_0'
          - level: 'kFTM_NoPwmSignal'
          - firstEdgeValueStr: '0'
          - dutyValueStr: '0'
          - enableComplementary: 'false'
          - enableDeadtime: 'false'
          - enable_chan_irq: 'false'
          - enable_chan1_irq: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ftm_config_t FTM1_config = {
  .prescale = kFTM_Prescale_Divide_1,
  .faultMode = kFTM_Fault_Disable,
  .faultFilterValue = 0,
  .deadTimePrescale = kFTM_Deadtime_Prescale_1,
  .deadTimeValue = 12,
  .pwmSyncMode = kFTM_SoftwareTrigger,
  .reloadPoints = 0,
  .extTriggers = kFTM_InitTrigger,
  .chnlInitState = 0,
  .chnlPolarity = 0,
  .bdmMode = kFTM_BdmMode_0,
  .useGlobalTimeBase = false
};

/* ftm_chnl_pwm_config_param_t в SDK ftm[2.2.3] содержит только 4 поля:
 * chnlNumber, level, dutyValue, firstEdgeValue.
 * Поля enableComplementary и enableDeadtime появились в более новых версиях.
 * Complementary и deadtime включаются отдельными вызовами в FTM1_init(). */
const ftm_chnl_pwm_config_param_t FTM1_combinedPwmSignalParams[] = { 
  {
    .chnlNumber     = kFTM_Chnl_0,
    .level          = kFTM_HighTrue,  /* активно-высокий сигнал на PTB2/PTB3 */
    .firstEdgeValue = 0,
    .dutyValue      = 0,
  }
};

static void FTM1_init(void) {
  FTM_Init(FTM1_PERIPHERAL, &FTM1_config);
  FTM_SetTimerPeriod(FTM1_PERIPHERAL, FTM1_TIMER_MODULO_VALUE);
  FTM_SetupPwmMode(FTM1_PERIPHERAL, FTM1_combinedPwmSignalParams,
                   sizeof(FTM1_combinedPwmSignalParams) / sizeof(ftm_chnl_pwm_config_param_t),
                   kFTM_CombinedPwm);
  /* Complementary: CH1 = инверсия CH0 (нижний ключ полумоста Q2) */
  FTM_SetComplementaryEnable(FTM1_PERIPHERAL, kFTM_Chnl_0, true);
  /* Deadtime: 100 нс = 12 тактов × (1/120МГц), prescale=1
   * DTVAL=12 задан в FTM1_config.deadTimeValue */
  FTM_SetDeadTimeEnable(FTM1_PERIPHERAL, kFTM_Chnl_0, true);
}

/***********************************************************************************************************************
 * ADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC0'
- type: 'adc12'
- mode: 'ADC12'
- custom_name_enabled: 'false'
- type_id: 'adc12_5324d28dd0212c08055a9d9cd4317082'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_adc12:
    - enable_irq: 'false'
    - adc_interrupt:
      - IRQn: 'ADC0_IRQn'
      - enable_interrrupt: 'disabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - adc12_config:
      - referenceVoltageSource: 'kADC12_ReferenceVoltageSourceVref'
      - clockSource: 'kADC12_ClockSourceAlt0'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - clockDivider: 'kADC12_ClockDivider1'
      - resolution: 'kADC12_Resolution12Bit'
      - sampleClockCount: '13'
      - enableContinuousConversion: 'false'
    - adc12HardwareCompareConfig:
      - hardwareCompareModeEnable: 'false'
    - adc12_hardware_average_mode: 'kADC12_HardwareAverageDisabled'
    - hardwareTrigger: 'true'
    - enableDMA: 'true'
    - doAutoCalibration: 'true'
    - offset: '0'
    - gain: '0'
    - adc12_channels_config:
      - 0:
        - channelName: ''
        - channelNumber: 'SE.1'
        - enableInterruptOnConversionCompleted: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const adc12_config_t ADC0_config = {
  .referenceVoltageSource = kADC12_ReferenceVoltageSourceVref,
  .clockSource = kADC12_ClockSourceAlt0,
  .clockDivider = kADC12_ClockDivider1,
  .resolution = kADC12_Resolution12Bit,
  .sampleClockCount = 13UL,
  .enableContinuousConversion = false
};
adc12_channel_config_t ADC0_channelsConfig[1] = {
  {
    .channelNumber = 1U,
    .enableInterruptOnConversionCompleted = false
  }
};
const adc12_hardware_average_mode_t ADC0_hardwareAverageConfig = kADC12_HardwareAverageDisabled;

static void ADC0_init(void) {
  /* Initialize ADC12 converter */
  ADC12_Init(ADC0_PERIPHERAL, &ADC0_config);
  /* Set to hardware trigger mode */
  ADC12_EnableHardwareTrigger(ADC0_PERIPHERAL, true);
  /* Configure hardware average mode */
  ADC12_SetHardwareAverage(ADC0_PERIPHERAL, ADC0_hardwareAverageConfig);
  /* Set the offset value for the conversion result */
  ADC12_SetOffsetValue(ADC0_PERIPHERAL, (uint32_t) 0);
  /* Set the gain value for the conversion result */
  ADC12_SetGainValue(ADC0_PERIPHERAL, 0);
  /* Perform auto calibration */
  ADC12_DoAutoCalibration(ADC0_PERIPHERAL);
  /* Enable generating the DMA trigger when conversion is completed */
  ADC12_EnableDMA(ADC0_PERIPHERAL, true);
}

/***********************************************************************************************************************
 * PDB0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PDB0'
- type: 'pdb'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'pdb_32eb8756416d042c4a30e2cf9bd8fca4'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PDB0'
- config_sets:
  - fsl_pdb:
    - clockConfig:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - pdb_config:
      - loadValueMode: 'kPDB_LoadValueOnCounterOverflow'
      - firstDivider: 'kPDB_PrescalerDivider1'
      - secondDivider: 'kPDB_DividerMultiplicationFactor1'
      - moduloValue_str: '5000'
      - triggerInputSource: 'kPDB_TriggerInput8'
      - initSWtrigger: 'false'
      - enableContinuousMode: 'false'
    - pdb_adc_triggering_config: []
    - pdb_dac_triggering_config: []
    - pdb_pulse_out_config: []
    - pdb_delay_interrupt_config:
      - actionAfterDelay: 'noAction'
      - delayValue_str: ''
    - pdb_interrupts_config:
      - interrupt_sel: ''
      - enable_irq: 'false'
      - interrupt:
        - IRQn: 'PDB0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* PDB counter configuration */
const pdb_config_t PDB0_config = {
  .loadValueMode = kPDB_LoadValueOnCounterOverflow,
  .prescalerDivider = kPDB_PrescalerDivider1,
  .dividerMultiplicationFactor = kPDB_DividerMultiplicationFactor1,
  .triggerInputSource = kPDB_TriggerInput8,
  .enableContinuousMode = false
};

static void PDB0_init(void) {
  /* PDB counter initialization */
  PDB_Init(PDB0_PERIPHERAL, &PDB0_config);
  /* MOD=5000 здесь — заглушка. Реальное значение MOD=750 устанавливается
   * в prv_PatchPeripherals(). PDB_DoLoadValues() вызывается в SPWM_RuntimeArm()
   * после PDB_Enable(true) — только тогда LDOK корректно защёлкивает значения. */
  PDB_SetModulusValue(PDB0_PERIPHERAL, 5000U);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* DMA (eDMA0/DMAMUX) инициализируется в board_init_ext.c :: prv_DMA_Init()
   * до вызова этой функции. Здесь только FTM1, ADC0, PDB0. */
  FTM1_init();
  ADC0_init();
  PDB0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
