/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MKE18F512xxx16
package_id: MKE18F512VLH16
mcu_data: ksdk2_0
processor_version: 13.0.1
external_user_signals:
  signals:
  - {id: '1'}
pin_labels:
- {pin_num: '33', pin_signal: ADC0_SE5/ADC1_SE15/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0, label: TAB_CAL, identifier: TAB_CAL}
- {pin_num: '34', pin_signal: ADC0_SE4/ADC1_SE14/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, label: STAR_STOP, identifier: STAR_STOP}
- {pin_num: '35', pin_signal: ADC2_SE15/PTC9/LPUART1_TX/FTM1_FLT1/LPUART0_RTS, label: FAULT_LED, identifier: FAULT_LED}
- {pin_num: '15', pin_signal: ACMP2_IN1/PTD15/FTM0_CH0, label: test, identifier: test}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '64', peripheral: CoreDebug, signal: SWD_DIO, pin_signal: PTA4/ACMP0_OUT/EWM_OUT_b/JTAG_TMS/SWD_DIO}
  - {pin_num: '63', peripheral: RCM, signal: RESET, pin_signal: PTA5/TCLK1/JTAG_TRST_b/RESET_b}
  - {pin_num: '62', peripheral: CoreDebug, signal: SWD_CLK, pin_signal: ACMP0_IN2/PTC4/FTM1_CH0/RTC_CLKOUT/EWM_IN/FTM1_QD_PHB/JTAG_TCLK/SWD_CLK}
  - {pin_num: '49', peripheral: ADC0, signal: 'SE, 1', pin_signal: ADC0_SE1/ACMP0_IN1/PTA1/FTM1_CH1/LPI2C0_SDAS/FXIO_D3/FTM1_QD_PHA/LPUART0_RTS/TRGMUX_OUT0}
  - {pin_num: '35', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: ADC2_SE15/PTC9/LPUART1_TX/FTM1_FLT1/LPUART0_RTS, direction: OUTPUT, gpio_init_state: 'false',
    pull_select: up, pull_enable: disable}
  - {pin_num: '34', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE4/ADC1_SE14/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, direction: INPUT, pull_select: up,
    pull_enable: enable, digital_filter: disable}
  - {pin_num: '33', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE5/ADC1_SE15/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0, direction: INPUT, pull_select: up, pull_enable: enable,
    digital_filter: disable}
  - {pin_num: '32', peripheral: FTM1, signal: 'CH, 0', pin_signal: ADC0_SE6/PTB2/FTM1_CH0/LPSPI0_SCK/FTM1_QD_PHB/TRGMUX_IN3, pull_select: down, digital_filter: enable}
  - {pin_num: '31', peripheral: FTM1, signal: 'CH, 1', pin_signal: ADC0_SE7/PTB3/FTM1_CH1/LPSPI0_SIN/FTM1_QD_PHA/TRGMUX_IN2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Clock Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);

    gpio_pin_config_t STAR_STOP_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 34)  */
    GPIO_PinInit(BOARD_INITPINS_STAR_STOP_GPIO, BOARD_INITPINS_STAR_STOP_PIN, &STAR_STOP_config);

    gpio_pin_config_t TAB_CAL_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 33)  */
    GPIO_PinInit(BOARD_INITPINS_TAB_CAL_GPIO, BOARD_INITPINS_TAB_CAL_PIN, &TAB_CAL_config);

    gpio_pin_config_t FAULT_LED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC9 (pin 35)  */
    GPIO_PinInit(BOARD_INITPINS_FAULT_LED_GPIO, BOARD_INITPINS_FAULT_LED_PIN, &FAULT_LED_config);

    /* PORTA1 (pin 49) is configured as ADC0_SE1 */
    PORT_SetPinMux(PORTA, 1U, kPORT_PinDisabledOrAnalog);

    /* PORTA4 (pin 64) is configured as SWD_DIO */
    PORT_SetPinMux(PORTA, 4U, kPORT_MuxAlt7);

    /* PORTA5 (pin 63) is configured as RESET_b */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAlt7);
    /* Configure digital filter */
    PORT_EnablePinsDigitalFilter(
        /* Digital filter is configured on port B */
        PORTB,
        /* Digital filter is configured for PORTB0 */
        PORT_DFER_DFE_2_MASK,
        /* Enable digital filter */
        true);
    /* Configure digital filter */
    PORT_EnablePinsDigitalFilter(
        /* Digital filter is configured on port B */
        PORTB,
        /* Digital filter is configured for PORTB0 */
          PORT_DFER_DFE_0_MASK
            /* Digital filter is configured for PORTB1 */
            | PORT_DFER_DFE_1_MASK,
        /* Disable digital filter */
        false);

    const port_pin_config_t STAR_STOP = {/* Internal pull-up resistor is enabled */
                                         kPORT_PullUp,
                                         /* Passive filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Pin is configured as PTB0 */
                                         kPORT_MuxAsGpio,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORTB0 (pin 34) is configured as PTB0 */
    PORT_SetPinConfig(BOARD_INITPINS_STAR_STOP_PORT, BOARD_INITPINS_STAR_STOP_PIN, &STAR_STOP);

    const port_pin_config_t TAB_CAL = {/* Internal pull-up resistor is enabled */
                                       kPORT_PullUp,
                                       /* Passive filter is disabled */
                                       kPORT_PassiveFilterDisable,
                                       /* Low drive strength is configured */
                                       kPORT_LowDriveStrength,
                                       /* Pin is configured as PTB1 */
                                       kPORT_MuxAsGpio,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       kPORT_UnlockRegister};
    /* PORTB1 (pin 33) is configured as PTB1 */
    PORT_SetPinConfig(BOARD_INITPINS_TAB_CAL_PORT, BOARD_INITPINS_TAB_CAL_PIN, &TAB_CAL);

    /* PORTB2 (pin 32) is configured as FTM1_CH0 */
    PORT_SetPinMux(PORTB, 2U, kPORT_MuxAlt2);

    PORTB->PCR[2] = ((PORTB->PCR[2] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown));

    /* PORTB3 (pin 31) is configured as FTM1_CH1 */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAlt2);

    /* PORTC4 (pin 62) is configured as SWD_CLK */
    PORT_SetPinMux(PORTC, 4U, kPORT_MuxAlt7);

    /* PORTC9 (pin 35) is configured as PTC9 */
    PORT_SetPinMux(BOARD_INITPINS_FAULT_LED_PORT, BOARD_INITPINS_FAULT_LED_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[9] = ((PORTC->PCR[9] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_PE_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pullup resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullUp)

                     /* Pull Enable: Internal pullup or pulldown resistor is not enabled on the corresponding pin. */
                     | PORT_PCR_PE(kPORT_PullDisable));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
