/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PORT_DFER_DFE_0_MASK 0x01u /*!<@brief Digital Filter Enable Mask for item 0. */
#define PORT_DFER_DFE_1_MASK 0x02u /*!<@brief Digital Filter Enable Mask for item 1. */
#define PORT_DFER_DFE_2_MASK 0x04u /*!<@brief Digital Filter Enable Mask for item 2. */

/*! @name PORTC9 (number 35), FAULT_LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_FAULT_LED_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_FAULT_LED_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_FAULT_LED_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_FAULT_LED_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_FAULT_LED_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTB0 (number 34), STAR_STOP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_STAR_STOP_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_STAR_STOP_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_STAR_STOP_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_STAR_STOP_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_STAR_STOP_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTB1 (number 33), TAB_CAL
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TAB_CAL_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_TAB_CAL_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_TAB_CAL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_TAB_CAL_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_TAB_CAL_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
